
#define DW2_VERSION_MAJOR ${DW2_VERSION_MAJOR}
#define DW2_VERSION_MINOR ${DW2_VERSION_MINOR}
#define DW2_VERSION_PATCH ${DW2_VERSION_PATCH}

#define BOOL_ON 1
#define BOOL_OFF 0

#define USE_TURBO_JPEG BOOL_${USE_TURBO_JPEG}
